field.formatter.settings.gesso_helper_gesso_button:
  type: mapping
  label: Gesso Button formatter settings
  mapping:
    button_sizes:
      type: string
      label: Button Sizes
    button_styles:
      type: string
      label: Button Styles
    icon_name:
      type: string
      label: Icon Name
    icon_is_hidden:
      type: boolean
      label: Icon is Hidden
    icon_label:
      type: string
      label: Icon Label
    icon_position:
      type: string
      label: Icon Position
    icon_direction:
      type: string
      label: Icon Direction
    modifier_classes:
      type: string
      label: Modifier Classes

field.formatter.settings.gesso_helper_icon_link:
  type: mapping
  label: Icon Link formatter settings
  mapping:
    icon_name:
      type: string
      label: Icon Name
    icon_is_hidden:
      type: boolean
      label: Icon is Hidden
    icon_label:
      type: string
      label: Icon Label
    icon_position:
      type: string
      label: Icon Position
    icon_direction:
      type: string
      label: Icon Direction
    modifier_classes:
      type: string
      label: Modifier Classes
