# Design Tokens
# Define basic design variables here.
gesso:
  palette:
    brand:
      blue:
        base: '#0071BC'
        light: '#4773aa'
        light-1: '#8ba6ca'
        light-2: '#dce4ef'
        dark: '#205493'
        dark-1: '#112E51'
      ocean-blue:
        base: '#1dc2ae'
        light: '#29e1cb'
        light-1: '#7efbe1'
        dark: '#008480'
        dark-1: '#0b4b3f'
    grayscale:
      white: '#ffffff'
      gray-1: '#f1f1f1'
      gray-2: '#e6e6e6'
      gray-3: '#adadad'
      gray-4: '#757575'
      gray-5: '#5c5c5c'
      gray-6: '#454545'
      gray-7: '#1b1b1b'
      black: '#000000'
    other:
      yellow:
        base: '#fad980'
        light: '#fff1d2'
      yellow-neon:
        base: '#ff0'
      green:
        base: '#94bfa2'
        light: '#e7f4e4'
      red:
        base: '#e31c3d'
        light: '#e59393'
        light-1: '#f9dede'
        dark: '#cd2026'
        dark-1: '#981b1e'
  box-shadow:
    0: none
    1: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)
    2: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23)
    3: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23)
    4: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22)
    5: 0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22)
  constrains:
    sm: 800px
    md: 1440px
    lg: 2200px
  breakpoints:
    mobile: 320px
    mobile-lg: 480px
    tablet: 640px
    mobile-menu: 699px
    tablet-lg: 880px
    desktop: 1024px
    desktop-lg: 1200px
    widescreen: 1400px
  colors:
    text:
      primary: grayscale.gray-7
      secondary: grayscale.gray-5
      on-light: grayscale.gray-7
      on-dark: grayscale.white
      link: brand.blue.base
      link-hover: brand.blue.dark
      link-active: brand.blue.dark
      link-visited: brand.blue.dark
    background:
      site: grayscale.white
    button:
      primary:
        background: brand.blue.base
        background-hover: brand.blue.dark
        background-active: brand.blue.dark-1
        border: brand.blue.base
        border-hover: brand.blue.dark
        text: grayscale.white
        text-hover: grayscale.white
        text-active: grayscale.white
      secondary:
        background: brand.ocean-blue.light-1
        background-hover: brand.ocean-blue.light
        background-active: brand.ocean-blue.base
        border: brand.ocean-blue.light-1
        border-hover: brand.ocean-blue.light
        text: brand.ocean-blue.dark-1
        text-hover: brand.ocean-blue.dark-1
        text-active: grayscale.gray-7
      base:
        background: grayscale.gray-4
        background-hover: grayscale.gray-5
        background-active: grayscale.gray-6
        border: grayscale.gray-4
        border-hover: grayscale.gray-5
        text: grayscale.white
        text-hover: grayscale.white
        text-active: grayscale.white
      disabled:
        background: grayscale.gray-1
        border: grayscale.gray-1
        text: grayscale.gray-3
      danger:
        background: other.red.base
        background-hover: other.red.dark
        background-active: other.red.dark-1
        border: other.red.base
        border-hover: other.red.dark
        text: grayscale.white
        text-hover: grayscale.white
        text-active: grayscale.white
      back-to-top:
        background: grayscale.gray-3
        background-hover: grayscale.gray-5
        color: grayscale.white
        color-hover: grayscale.white
    form:
      background: grayscale.gray-1
      background-active: grayscale.white
      background-checked: brand.blue.base
      background-unchecked: grayscale.white
      border: grayscale.gray-2
      border-dark: grayscale.gray-5
      border-light: grayscale.gray-1
      thumb: grayscale.gray-5
      track: grayscale.gray-3
    mark:
      background: other.yellow-neon.base
      text: grayscale.gray-7
    selection:
      background: brand.blue.base
      text: grayscale.white
    table:
      border: grayscale.gray-5
      background: grayscale.white
      background-head: grayscale.gray-1
      background-foot: grayscale.gray-1
    ui:
      generic:
        background: grayscale.gray-3
        background-darker: grayscale.gray-7
        background-dark: grayscale.gray-6
        background-light: grayscale.gray-1
        background-lighter: grayscale.gray-1
        border: grayscale.gray-3
        border-dark: grayscale.gray-6
        border-light: grayscale.gray-1
        text-lighter: grayscale.white
        text-light: grayscale.gray-3
        text-dark: grayscale.gray-5
        text-darker: grayscale.gray-7
        accent: brand.blue.base
        accent-dark: brand.blue.dark-1
        accent-light: brand.blue.light
        focus: brand.blue.light
      error:
        background: other.red.light-1
        border: other.red.light
      success:
        background: other.green.light
        border: other.green.base
      warning:
        background: other.yellow.light
        border: other.yellow.base
  typography:
    font-family:
      primary:
        name: Primary
        stack: '"Source Sans Pro", Arial, sans-serif'
      system:
        name: System
        stack: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Oxygen-Sans", Ubuntu, Cantarell, "Fira Sans", Droid Sans, sans-serif'
      monospace:
        name: Monospace
        stack: 'Menlo, Consolas, "Lucida Console", "Liberation Mono", "Courier New", monospace, sans-serif'
    base-font-size: 16px
    font-size:
      1: 12px
      2: 14px
      3: 16px
      4: 20px
      5: 25px
      6: 31.25px
      7: 39.06625px
      8: 48.8281px
      9: 61.0352px
      10: 76.2939px
    responsive-font-size-min-width: 360px
    responsive-font-size-max-width: 1600px
    responsive-font-size:
      1:
        min: 12px
        val: auto
        max: 12px
      2:
        min: 14px
        val: auto
        max: 14px
      3:
        min: 16px
        val: auto
        max: 16px
      4:
        min: 18px
        val: auto
        max: 20px
      5:
        min: 20.25px
        val: auto
        max: 25px
      6:
        min: 22.7813px
        val: auto
        max: 31.25px
      7:
        min: 25.6289px
        val: auto
        max: 39.0625px
      8:
        min: 28.8325px
        val: auto
        max: 48.8281px
      9:
        min: 32.4366px
        val: auto
        max: 61.0352px
      10:
        min: 36.4912px
        val: auto
        max: 76.2939px
    font-weight:
      light: 300
      regular: 400
      semibold: 600
      bold: 700
    line-height:
      tight: 1.1
      base: 1.45
      loose: 1.7
    display:
      display:
        color: text.primary
        font-family: primary.stack
        font-weight: bold
        line-height: tight
        responsive-font-size: 10
      h1:
        color: text.primary
        font-family: primary.stack
        font-weight: bold
        line-height: tight
        responsive-font-size: 8
      h2:
        color: text.primary
        font-family: primary.stack
        font-weight: bold
        line-height: tight
        responsive-font-size: 7
      h3:
        color: text.primary
        font-family: primary.stack
        font-weight: bold
        line-height: tight
        responsive-font-size: 6
      h4:
        color: text.primary
        font-family: primary.stack
        font-weight: bold
        line-height: base
        responsive-font-size: 5
      h5:
        color: text.primary
        font-family: primary.stack
        font-weight: bold
        line-height: base
        responsive-font-size: 3
      h6:
        color: text.primary
        font-family: primary.stack
        font-weight: semibold
        letter-spacing: -0.04em
        line-height: loose
        text-transform: uppercase
        responsive-font-size: 2
      blockquote:
        color: text.link
        font-family: primary.stack
        font-size: 5
        font-weight: regular
        line-height: base
      body:
        color: text.primary
        font-family: primary.stack
        font-size: 3
        font-weight: regular
        line-height: base
      body-large:
        color: text.primary
        font-family: primary.stack
        font-size: 4
        font-weight: regular
        line-height: base
      cite:
        color: text.secondary
        font-family: primary.stack
        font-size: 2
        font-style: normal
        font-weight: semibold
        letter-spacing: .02em
        line-height: tight
  transitions:
    ease:
      ease-in-out: 'cubic-bezier(0.4, 0, 0.2, 1)'
      ease-out: 'cubic-bezier(0.0, 0, 0.2, 1)'
      ease-in: 'cubic-bezier(0.4, 0, 1, 1)'
      sharp: 'cubic-bezier(0.4, 0, 0.6, 1)'
    duration:
      shortest: 150ms
      short: 200ms
      standard: 375ms
      long: 400ms
      intro: 270ms
      outro: 195ms
  z-index:
    nav: 1000
    drawer: 1200
    modal: 1300
  spacing:
    0: 0
    0.5: 4px
    1: 8px
    1.5: 12px
    2: 16px
    2.5: 20px
    3: 24px
    4: 32px
    5: 40px
    6: 48px
    7: 56px
    8: 64px
    9: 72px
    10: 80px
    12: 96px
    15: 120px
  gutter-width: 40px
  site-margins:
    'mobile': 16px
    'desktop': 32px
